esphome:
  name: "ac-test"
  friendly_name: Test AC
  min_version: 2024.11.0
  name_add_mac_suffix: false

external_components:
  - source: components

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {}

remote_receiver:
  pin:
    number: GPIO14
    inverted: True
    mode: OUTPUT_OPEN_DRAIN
  tolerance: 55%
  id: ir_receiver
  buffer_size: 2kb

remote_transmitter:
  carrier_duty_percent: 50%
  pin:
    number: GPIO4
    inverted: True
    mode: OUTPUT_OPEN_DRAIN

climate:
  - platform: panaac
    name: "Remote Controller"
    receiver_id: ir_receiver
    supports_heat: True
    supports_quiet: True
    fan_5level: True
    swing_horizontal: True
    temp_step: 0.5
    
    