substitutions:
  ap_prefix: !secret wifi_ap_ssid_prefix
  device_name: "ac-test-2"
  device_friendlyname: "AC Test Non-invasive"

esphome:
  name: "${device_name}"
  friendly_name: "${device_friendlyname}"
  min_version: 2025.9.0
  name_add_mac_suffix: false

external_components:
  - source: components

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${ap_prefix}.${device_name}"
    password: !secret wifi_ap_password

captive_portal:

remote_receiver:
  pin:
    number: GPIO14
    inverted: True
  tolerance: 55%
  id: ir_receiver
  idle: 5ms

remote_transmitter:
  carrier_duty_percent: 50%
  pin:
    number: GPIO13

climate:
  - platform: panaac
    name: "Remote Controller"
    receiver_id: ir_receiver
    supports_fan_only: true
    supports_heat: true
    supports_quiet: True
    fan_5level: True
    swing_horizontal: True
    temp_step: 0.5
    ir_control: True